- hi
  - <hi/hey/hello/hola>
    - 0
      - hey, hello, hola
- createkeybind
  - <createkeybind> <key> <operation>
    - 2
      -
- what
  - <what/what's> <question>
    - 1
      - what's, whats
- how
  - <how/how's/how'd> <question>
    - 1
      - how's, how'd
- math
  - <math>
    - 0
     - 
- open
  - <open> <program file location>
    - 1
      - launch, start