- hi
  - <hi/hey/hello/hola>
    - 0
      - hey, hello, hola
- createkeybind
  - <createkeybind> <key> <operation>
    - 2
      - 
- what
  - <what/what's> <question>
    - 1
      - what's
- math
  - <math>
    - 0
      - 
- how
  - <how/how's/how'd> <question>
    - 1
      - how's, how'd
- clear
  - <clear>
    - 0
      - cl
